package com.gmt.myschool.enums;

public enum UserTypes {
	GAURDIAN, TEACHER, SCHOOL_ADMIN, SCHOOL_CLEARK, STUDENT, SUPER_ADMIN, ADMIN, OPERATOR, MONITOR, DRIVER, CONDUCTOR, CLEANER, CARE_TAKER, SECURITY
}
